name: Actions Workflow

on: 
   push:
    branches: 
      - master
      - 'feature/*'  #matches feature/featA, feature/featB but does not match feature/feat/a
      - 'feature/**'
      - '!feature/featC'  #this is to exclude the push on some branches
#    branches-ignore:
#         - null  
#     schedule:
#       - cron: "0/2 * * * *"
#       - cron: "0/3 * * * *"
#    [push, pull_request]
#     pull_request:
#       types: [closed, assigned, opened, reopened]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
        - name: List Files
          run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
        - name: Checkout
          uses: actions/checkout@v3
        - name: List Files After Checkout
          run: |
            pwd
            ls -a
        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Peter
        - name: Log greeting time  
          run : echo "${{steps.greet.outputs.time}}"